#参照ruicky

name: 多看点
on:
    push:
        branches:
            - main
    schedule:
        - cron: '28 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: 多看点
              uses: actions/setup-node@v1
              with:
                node-version: '14.x'
            - name: Run
              run: npm install
            - run: node dkd.js
              env:
                dkdurl: ${{ secrets.dkdurl }}
                dkdbody: ${{ secrets.dkdbody }}
                sckey: ${{ secrets.sckey }}
                dkdhd: ${{ secrets.dkdhd }}
